### Why Neural Net and Deep Learning?

* deep learning has more freedom, so can obtain more sophisticated decision region for classification problem for example
* deep learing accepts non-tabular data, for example images, voice, text data
* deep learning can extract features ML could not
* we can build two DL models for two different but related dataset and connect their layers for providing decision (classification for example)
* the more data we have, the better performance usually we can get from DL model
* DL transforms memory heavy computation into iterative CPU heavy computation. For example, user-user collaborative recommender system can be modeled as embedded user-item neural net. For the first one, we should create and save Big Matrix

## Vector, Matrix and Tensor

<img src= "https://hackernoon.com/photos/4HK5qyMbWfetPhAavzyTZrEb90N2-gr23tjy" width="600" height="600" />

## Make a vector in numpy

In [2]:
import numpy as np

# 1D tensor, this is not accepted by keras, tensorflow etc.
vector = np.array([5, 2, 1])
print(vector)

[5 2 1]


In [20]:
print(vector.shape)   # the number of items in the array

(3,)


In [10]:
vector[1]    # item at the second index

2

In [19]:
# this is a row matrix (2D tensor) this is accepted!

v = np.array([[5, 2, 1]])
print(v.shape)    # (1, 3) this says that we have one sample and this sample has 3 features

(1, 3)


In [23]:
print(v[0])

v[0][1]

[5 2 1]


2

In [22]:
# this is a column matrix (2D tensor)

v_t = np.transpose(v)

print(v_t)
v_t.shape   # (3, 1) this says that there are 3 samples, each with one feature

[[5]
 [2]
 [1]]


(3, 1)

## Make a matrix in numpy

In [25]:
v = np.array([[1, 2, 3], [2, 0, 1]])

print(v)

print(v.shape)    # (2, 3) says that there are 2 samples each with 3 features

# .size returns the number of elements
print(v.size)   

[[1 2 3]
 [2 0 1]]
(2, 3)
6


In [28]:
v_t = np.transpose(v)   # changes the items in the first row, into its own row
print(v_t)
print(v_t.shape)
print(v_t.size)

[[1 2]
 [2 0]
 [3 1]]
(3, 2)
6


## Arrange or Reshape the matrix (2D array or 2D Tensor)

In [32]:
v = np.array([[1,2,3],[2, 0, 1]])
print(v.reshape(3,2))       # rearranges the original matrix to have 3 rows and 2 columns

# By applying the following reshape, we transform the matrix into 3D Tensor

print(v.reshape(3,1,2))

print(v.reshape(-1,1,2))

[[1 2]
 [3 2]
 [0 1]]
[[[1 2]]

 [[3 2]]

 [[0 1]]]
[[[1 2]]

 [[3 2]]

 [[0 1]]]


## Make a 3D Tensor in numpy

In [33]:
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)

# The first element of shape shows how many shapes we have, 
# and the second and third elements shows the  row and column dimensions

print(v.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]
(2, 2, 3)


In [34]:
print(v[0])    # returns the front matrix


[[1. 2. 3.]
 [4. 5. 6.]]


In [35]:
print(v[1])    # returns the back matrix

[[ 7.  8.  9.]
 [11. 12. 13.]]


In [40]:
print(v.size)

12


### Change the 3D tensor into a 1D tensor
* a 1D tensor is just 1 column

In [39]:
a = v.reshape(12,1)
print(a)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [11.]
 [12.]
 [13.]]


## Matrix multiplication  

https://www.khanacademy.org/math/precalculus/precalc-matrices/properties-of-matrix-multiplication/a/properties-of-matrix-multiplication

In [3]:
a = np.array([[4, 2, 3],[2, 0, 1]])

b = np.transpose(a)

c = np.dot(a,b)

print(c)

[[29 11]
 [11  5]]


## Element-wise multiplication of matrix

In [4]:
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
print(np.multiply(a,b))
print(np.multiply(b,a))
print(a*b)
print(b*a)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
